// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaludConecta.Infrastructure.Data.Context;

#nullable disable

namespace SaludConecta.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SaludConectaDbContext))]
    partial class SaludConectaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SaludConecta.Core.Entities.Alergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaDiagnostico")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Moderada");

                    b.Property<string>("TipoAlergia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilPacienteId");

                    b.HasIndex("PerfilPacienteId", "Activa");

                    b.ToTable("Alergias", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.AntecedenteHeredofamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondicionMedicaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ParentescoFamiliar")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CondicionMedicaId");

                    b.HasIndex("PerfilPacienteId");

                    b.HasIndex("PerfilPacienteId", "ParentescoFamiliar", "CondicionMedicaId")
                        .IsUnique();

                    b.ToTable("AntecedentesHeredofamiliares", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.AntecedentePersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CondicionMedicaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaDiagnostico")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CondicionMedicaId");

                    b.HasIndex("PerfilPacienteId");

                    b.HasIndex("PerfilPacienteId", "CondicionMedicaId")
                        .IsUnique();

                    b.ToTable("AntecedentesPersonales", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.AntecedentePsicologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaDiagnostico")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCondicion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NotasTratamiento")
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilPacienteId");

                    b.ToTable("AntecedentesPsicologicos", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.ArchivoAdjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("EstudioClinicoId")
                        .HasColumnType("int");

                    b.Property<string>("ExtensionArchivo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<int?>("RecetaId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("EstudioClinicoId");

                    b.HasIndex("PerfilPacienteId");

                    b.HasIndex("RecetaId");

                    b.HasIndex("TipoArchivo");

                    b.ToTable("ArchivosAdjuntos", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.CatalogoCondicionMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NombreCondicion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Categoria", "NombreCondicion")
                        .IsUnique();

                    b.ToTable("CatalogoCondicionesMedicas", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.CodigoVerificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaExpiracion");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CodigosVerificacion", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnostico")
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaSeguimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEspecialista")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Especialidad");

                    b.HasIndex("PerfilPacienteId", "FechaConsulta")
                        .IsDescending(false, true);

                    b.ToTable("Consultas", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.EstudioClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaResultados")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Laboratorio")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MedicoSolicitante")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreEstudio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoEstudio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("PerfilPacienteId");

                    b.HasIndex("PerfilPacienteId", "TipoEstudio");

                    b.ToTable("EstudiosClinicos", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.EventoQuirurgico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hospital")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Medico")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilPacienteId");

                    b.HasIndex("PerfilPacienteId", "TipoEvento");

                    b.ToTable("EventosQuirurgicos", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.MedicamentoReceta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("FrecuenciaHoras")
                        .HasColumnType("int");

                    b.Property<string>("Instrucciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NombreMedicamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.Property<string>("ViaAdministracion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Oral");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.HasIndex("Activo", "FechaFin");

                    b.ToTable("MedicamentosReceta", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.PerfilEstiloVida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadFisica")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AntecedentesLaborales")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasDefaultValue("Ninguno");

                    b.Property<string>("CalidadAlimentacion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CalidadVida")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ConsumoAlcohol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Ninguno");

                    b.Property<string>("ConsumoDrogas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Ninguno");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<decimal?>("HorasSueno")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("MedicamentosActuales")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasDefaultValue("Ninguno");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Tabaquismo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("Ninguno");

                    b.Property<int?>("VasosAguaDiarios")
                        .HasColumnType("int");

                    b.Property<string>("Zoonosis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("No");

                    b.HasKey("Id");

                    b.HasIndex("PerfilPacienteId")
                        .IsUnique();

                    b.ToTable("PerfilEstiloVida", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.PerfilPaciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("ColorAvatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasDefaultValue("#6366F1");

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LugarNacimiento")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Yo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TelefonoEmergencia")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Desconocido");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "Activo");

                    b.ToTable("PerfilesPaciente", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.ProveedorAutenticacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("HashContrasena")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProveedoresAutenticacion", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaReceta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<string>("RecetadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("PerfilPacienteId");

                    b.HasIndex("PerfilPacienteId", "Activa");

                    b.ToTable("Recetas", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("DispositivoInfo")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Revocado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.RegistroBiometrico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("EstaturaCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notas")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("PerfilPacienteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PesoKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilPacienteId", "FechaRegistro")
                        .IsDescending(false, true);

                    b.ToTable("RegistrosBiometricos", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Personal");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("TelefonoVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Alergia", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("Alergias")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.AntecedenteHeredofamiliar", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.CatalogoCondicionMedica", "CondicionMedica")
                        .WithMany("AntecedentesHeredofamiliares")
                        .HasForeignKey("CondicionMedicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("AntecedentesHeredofamiliares")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CondicionMedica");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.AntecedentePersonal", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.CatalogoCondicionMedica", "CondicionMedica")
                        .WithMany("AntecedentesPersonales")
                        .HasForeignKey("CondicionMedicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("AntecedentesPersonales")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CondicionMedica");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.AntecedentePsicologico", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("AntecedentesPsicologicos")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.ArchivoAdjunto", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.Consulta", "Consulta")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SaludConecta.Core.Entities.EstudioClinico", "EstudioClinico")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("EstudioClinicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaludConecta.Core.Entities.Receta", "Receta")
                        .WithMany("ArchivosAdjuntos")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Consulta");

                    b.Navigation("EstudioClinico");

                    b.Navigation("PerfilPaciente");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.CodigoVerificacion", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.Usuario", "Usuario")
                        .WithMany("CodigosVerificacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Consulta", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.EstudioClinico", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.Consulta", "Consulta")
                        .WithMany("EstudiosClinicos")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("EstudiosClinicos")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.EventoQuirurgico", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("EventosQuirurgicos")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.MedicamentoReceta", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.Receta", "Receta")
                        .WithMany("Medicamentos")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.PerfilEstiloVida", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithOne("PerfilEstiloVida")
                        .HasForeignKey("SaludConecta.Core.Entities.PerfilEstiloVida", "PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.PerfilPaciente", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.Usuario", "Usuario")
                        .WithMany("PerfilesPaciente")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.ProveedorAutenticacion", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.Usuario", "Usuario")
                        .WithMany("ProveedoresAutenticacion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Receta", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.Consulta", "Consulta")
                        .WithMany("Recetas")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("Recetas")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.RegistroBiometrico", b =>
                {
                    b.HasOne("SaludConecta.Core.Entities.PerfilPaciente", "PerfilPaciente")
                        .WithMany("RegistrosBiometricos")
                        .HasForeignKey("PerfilPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerfilPaciente");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.CatalogoCondicionMedica", b =>
                {
                    b.Navigation("AntecedentesHeredofamiliares");

                    b.Navigation("AntecedentesPersonales");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Consulta", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("EstudiosClinicos");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.EstudioClinico", b =>
                {
                    b.Navigation("ArchivosAdjuntos");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.PerfilPaciente", b =>
                {
                    b.Navigation("Alergias");

                    b.Navigation("AntecedentesHeredofamiliares");

                    b.Navigation("AntecedentesPersonales");

                    b.Navigation("AntecedentesPsicologicos");

                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("Consultas");

                    b.Navigation("EstudiosClinicos");

                    b.Navigation("EventosQuirurgicos");

                    b.Navigation("PerfilEstiloVida");

                    b.Navigation("Recetas");

                    b.Navigation("RegistrosBiometricos");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Receta", b =>
                {
                    b.Navigation("ArchivosAdjuntos");

                    b.Navigation("Medicamentos");
                });

            modelBuilder.Entity("SaludConecta.Core.Entities.Usuario", b =>
                {
                    b.Navigation("CodigosVerificacion");

                    b.Navigation("PerfilesPaciente");

                    b.Navigation("ProveedoresAutenticacion");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
